project_id = "wwyyfgngdwaabzwzvlml"

[functions.submit-booking]
verify_jwt = false

[functions.create-booking-checkout]
verify_jwt = false

[functions.payments-webhook]
verify_jwt = false

[functions.check-booking-status]
verify_jwt = false

[functions.send-booking-emails]
verify_jwt = false

[functions.scheduled-email-runner]
verify_jwt = false
